### ISSUE TITLE
Compilation errors with main branch

### ISSUE THREAD

**Issue by a759116** [hyperledger/anoncreds-v2-rs#33]
After the last merge, the main branch has problems in map_credentials and map_presentation code. The last change was updating base64 = "0.22.1".

**Comment by haroldcarr** [comment]
see:
- https://github.com/hyperledger/anoncreds-v2-rs/pull/24#issuecomment-2254996672
- https://github.com/hyperledger/anoncreds-v2-rs/pull/24#issuecomment-2256871308

**Comment by a759116** [comment]
Hi @haroldcarr ,
Thanks for your response. I cloned the latest main branch which has "base64 = "0.22.1". This was the last merge. The code files map_credentials and map_presentation broke after this change. They work with 0.13.0. Did you try the latest code and if that work for you?

<img width="202" alt="image" src="https://github.com/user-attachments/assets/2e2cbd3a-160d-4662-ae84-3eedc177384d">
<img width="295" alt="image" src="https://github.com/user-attachments/assets/4877ee86-d257-403d-868b-a4b5713dc9fe">

**Comment by haroldcarr** [comment]
the main branch is broken

**Comment by a759116** [comment]
This is fixed now.
